services:
  - type: web
    name: bot-telegram
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: bot-telegram-db
          property: connectionString
    
databases:
  - name: bot-telegram-db
    databaseName: bot_telegram
    user: bot_telegram_user
